const Icons = {
  Giftcard_img: require("../images/home/giftcard.png"),
  StoreCredit_img: require("../images/home/store.png"),
  Automation_img: require("../images/home/automation.png"),
  Loyalty_img: require("../images/home/loyalty.png"),
  Refferal_img: require("../images/home/refferal.png"),
  Coupons_img: require("../images/home/coupon.png"),
  Wallet_img: require("../images/home/wallet.png"),
  Woo: require("../images/trusted-merchents/woo.png"),
  Shopify: require("../images/trusted-merchents/shopify.png"),
  Commerce: require("../images/trusted-merchents/commerce.png"),
  Miva: require("../images/trusted-merchents/miva.png"),
  BigCommerce: require("../images/integrations/BigCommerce.png"),
  Kalviyo: require("../images/integrations/Kalviyo.png"),
  Omnisend: require("../images/integrations/Omnisend.png"),
  FeatureImg: require("../images/home/feature_img.png"),
  Pinstrips: require("../images/trusted-merchents/pinstrip.png"),
  Besttop: require("../images/trusted-merchents/bestop.png"),
  Cornor: require("../images/trusted-merchents/cornor.png"),
  Cariloha: require("../images/trusted-merchents/cariloha.png"),
  Fylnn: require("../images/trusted-merchents/fylnn.png"),
  Giftcard: require("../images/home/giftcard.png"),
  Author_01: require("../images/testimonials/01.png"),
  Besttop_01: require("../images/testimonials/bestop1.png"),
  GiftBanner: require("../images/giftcard/giftBanner.png"),
  Giftcard_01: require("../images/giftcard/giftcard.png"),
  Ellipse_01: require("../images/giftcard/ellipse_01.png"),
  Ellipse_02: require("../images/giftcard/ellipse_02.png"),
  Report: require("../images/giftcard/report.png"),
  Reload: require("../images/giftcard/reload.png"),
  OnBoarding: require("../images/home/onboarding.png"),
  CrossSell: require("../images/home/crosssell.png"),
  Upsell: require("../images/home/upsell.png"),
  Refund: require("../images/home/refund.png"),
  Reward: require("../images/home/reward.png"),
};

export default Icons;
