export * from "./banners.config";
export * from "./trustedMerchants.config";
export * from "./footer.config";
export * from "./testimonial.config";
export * from "./homePage.config";
export * from "./giftcardPage.config";
export * from "./loyaltyPage.config";
export * from "./referralPage.config";
export * from "./route.config";
export * from "./priceList.config";
export { default as Constants } from "./constants";
